name: new_website
description: Puzzak.Page 2.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  intl: ^0.20.2
  dynamic_color: ^1.6.9
  http: ^1.2.1
  system_theme: 3.1.2
  flutter_svg: ^2.0.10+1
  provider: ^6.0.5
  go_router: ^12.0.0
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/authors.json
    - assets/puzzak_av.jpg
    - assets/profile.jpg
    - assets/dashboard-project.png
    - assets/autostream-project.png
    - assets/links-project.png
    - assets/map-project.png
    - assets/secret-project.png
    - pubspec.yaml
